# Generated by Django 3.2.25 on 2024-05-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
    ]
